# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 00:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('room', models.PositiveSmallIntegerField(default=0)),
                ('ubnumber', models.PositiveSmallIntegerField(default=0)),
                ('period', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
